name: "release"

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    name: Create release
    steps:
      - name: Checkout api-gateway repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Define release
        uses: paulhatch/semantic-version@4.0.2
        with:
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          patch_pattern: "fix:"
          format: "${major}.${minor}.${patch}"
          namespace: test
          short_tags: false
          bump_each_commit: false
