name: "tag"

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  create-tag:
    runs-on: ubuntu-latest
    name: Create tag
    steps:
      - name: Checkout api-gateway repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Define version
        run: |
          exist_tag=$(git tag)
          last_tag=""

          if [[ -n "$exist_tag" ]]; then
              last_tag=$(git describe --abbrev=0 --tags)
          fi

          major=0
          minor=0
          patch=0

          echo "========LAST tag========"
          echo "$last_tag"

          if [[ $last_tag =~ ^[0-9]+.[0-9]+.[0-9]+$ ]]; then
              IFS='.' read -ra ELEM <<< "$last_tag"
              major=${ELEM[0]}
              minor=${ELEM[1]}
              patch=${ELEM[2]}
          fi

          last_commit=$(git log -1 --pretty=%B)
          echo "========LAST commit========"
          echo "$last_commit"

          version_upgraded=1

          case $last_commit in

              "breaking change:"*)
                  echo "Creating major release"
                  major="$((major+1))"
                  ;;

              "feat:"*)
                  echo "Creating minor release"
                  minor="$((minor+1))"
                  ;;

              "fix:"*)
                  echo "Creating patch release"
                  patch="$((patch+1))"
                  ;;

              *)
                  echo "Without version upgrade"
                  version_upgraded=0
                  ;;
          esac

          export TAG_VERSION="na"
          if [[ $version_upgraded == 1 ]]; then 
              TAG_VERSION="$major.$minor.$patch"
              echo "::set-env name=TAG_VERSION::$TAG_VERSION"
          fi


      - name: Create tag
        run: |
          if [[ "$TAG_VERSION" == "na"]]; then
            echo "The tag will not be created"
            exit 0
          fi
          git tag $TAG_VERSION
          git push --tags
          

          

